import type { ResponseFor, TaskModel } from '@research-agent-platform/contracts';
import { escapeHtml as e } from './view-model';
import { taskCard, planCard } from './collaboration-view';
export type Planning = ResponseFor<'getPlanRequest'>['data'];
export type Run = ResponseFor<'getRun'>['data'];
export const runLabels:Record<Run['status'],string>={queued:'已排队',running:'正在运行',waiting_input:'等待输入',failed:'失败',interrupted:'已中断',cancelled:'已取消',succeeded:'候选产物已生成'};
export function usage(value:Run['usageDetail']):string {
 return `<p class="fine">输入 tokens：${value?.inputTokens??'未知'} · 输出 tokens：${value?.outputTokens??'未知'} · 耗时：${value?value.elapsedMs+' ms':'未知'} · 费用：${value?.cost==null?'未知':e(String(value.cost)+' '+(value.currency??''))}</p>`;
}
export function planningView(p:Planning,name:(id:string)=>string):string {
 const states:Record<Planning['status'],string>={queued:'已排队',running:'正在生成',draft:'建议草案已保存',ready:'授权查询已返回',waiting_input:'等待输入',failed:'生成失败',interrupted:'生成已中断',cancelled:'生成已取消'};
 const reply=p.reply;
 return `<section class="flow"><a class="back" href="#/">← 返回入口</a><h1>${states[p.status]}</h1><p class="fine">请求版本 ${p.version} · 更新 ${e(p.updatedAt)} · 可收藏当前链接，重新打开从服务读取。</p><p>生成在后台进行，完成后显示完整、可编辑的草案。可以离开页面，稍后从当前链接继续查看。</p>${p.failure?`<p class="alert" role="alert">${e(p.failure)}。可以返回入口手工创建方案；重新发起是新请求。</p>`:''}${usage(p.usage)}${reply?`<p class="banner">${reply.origin==='model_suggestion'?'模型建议 · 尚未确认或承诺':'授权服务事实 · 不由模型编造进度'} · 读取 ${e(reply.readAt)} · 回复契约 ${e(reply.replyVersion)}</p>${reply.gaps.length?`<section class="panel"><h2>缺口与匹配依据</h2><ul>${reply.gaps.map(g=>`<li>${e(g)}</li>`).join('')}</ul></section>`:''}${reply.plan?`<h2>继续编辑同一草案</h2>${planCard(reply.plan)}<p>日期、分工和缺材料仍需核对；打开后重新读取最新版本，再明确确认。此回复不自动派发。</p>`:''}${reply.intent!=='draft'?`<h2>${reply.intent==='find_work'?'可承接候选':'当前任务进展'}</h2><p class="fine">仅展示服务授权的任务；以公开资料与服务返回的缺口为依据，不推断私人能力或人员负荷。</p>${reply.tasks.map(t=>taskCard(t,name)).join('')||'<p>没有符合当前授权范围的结果。</p>'}${reply.truncated?'<p>仅返回前 20 项，更多任务请进入实验室总览。</p>':''}`:''}<p class="fine">历史回复只是读取时的建议或事实。所有动作进入对象后重新校验当前版本与权限。</p>`:''}${['queued','running','waiting_input','interrupted'].includes(p.status)?`<form data-form="cancel-planning" class="panel"><label>取消原因<textarea name="planning-cancel-reason" required maxlength="8000"></textarea></label><button>取消这次生成</button></form>`:''}<button type="button" data-action="refresh">读取最新状态</button></section>`;
}
export function runView(r:Run,task:TaskModel):string {
 const candidate=r.candidate;
 return `<article class="panel run" data-run="${e(r.id)}"><h3>${runLabels[r.status]}</h3><p class="fine">运行 ${e(r.id)} · v${r.version} · 任务绑定 v${r.taskVersion} / 当前 v${task.version} · 尝试 ${r.attempt}/${r.maxAttempts}</p><p>${e(r.capability.id)} · 能力 v${r.capability.version} · ${e(r.provider)} / ${e(r.model)} · Harness ${e(r.harnessVersion)}</p><p class="fine">累计预算 ${r.budget.maxTokens} tokens / ${r.budget.maxSeconds} 秒；${r.nextAttemptAt?'服务计划下次尝试 '+e(r.nextAttemptAt):'没有自动重试计划'}。未知用量不当作零。</p>${usage(r.usageDetail)}${r.failure?`<p class="alert">${e(r.failure)}</p>`:''}<p>输入：${r.inputs.map(i=>`${e(i.id)} v${i.version} · SHA256 ${e(i.sha256)}`).join('；')||'尚无已授权文本材料'}</p>${candidate?`<section class="candidate"><h4>${e(candidate.title)}</h4><p class="banner">可审查候选，不等于交付已提交或任务已验收。引文匹配原材料，不代表外部科学核验。</p>${candidate.items.map(item=>`<section><h4>${e(item.requirement)}</h4><p>${item.assessment==='gap'?'存在缺口':'有输入材料支持'}</p>${item.gap?`<p>${e(item.gap)}</p>`:''}${item.citations.map(c=>`<blockquote>${e(c.quote)}<footer>来源附件 ${e(c.artifactId)}（在本任务附件区授权下载核对）</footer></blockquote>`).join('')}</section>`).join('')}<ul>${candidate.limitations.map(l=>`<li>${e(l)}</li>`).join('')}</ul></section>`:''}${r.candidateDeliverableId?`<p>已提交为交付 ${e(r.candidateDeliverableId)}，验收结果以交付记录为准。</p>`:''}<div class="actions">${r.allowedActions.includes('submit_candidate')?`<button type="button" data-action="submit-run-${e(r.id)}">确认提交此候选为交付</button>`:''}${r.allowedActions.includes('retry')?`<button type="button" data-action="retry-run-${e(r.id)}">按原累计预算重试此运行</button><p class="fine">重试前请在下方“能力、材料与新运行授权”选择当前授权文本；重试使用原累计预算。</p>`:''}</div>${r.allowedActions.includes('cancel')?`<form data-form="cancel-run-${e(r.id)}"><label>取消原因<textarea name="run-cancel-${e(r.id)}" required maxlength="8000"></textarea></label><button>取消此运行</button></form>`:''}</article>`;
}
