import { z } from 'zod'
import { Id, Title, Text, Version, Instant, ObjectRef, PublicCapabilityRef, Budget, Schedule, ModelUsage, ErrorResponse, errorStatus, data, page } from './models.js'

export const chatProtocolVersion = '1.6.0' as const
export const ChatAvailability = z.strictObject({ status: z.enum(['available', 'unavailable', 'disabled']), reason: z.enum(['platform_disabled', 'lab_disabled', 'missing_credentials', 'capability_unavailable', 'owner_authorization_required', 'not_connected']).nullable() })
export const ContactProfileInput = z.strictObject({ displayName: Title, introduction: z.string().max(2000), capabilityDescription: z.string().max(4000), personality: z.string().max(2000) })
export const ContactProfile = z.strictObject({ role: z.enum(['human', 'coordinator', 'specialist', 'public_capability']), introduction: z.string().max(2000), capabilityDescription: z.string().max(4000), personality: z.string().max(2000), version: Version })
export const ContactRelationship = z.strictObject({ status: z.enum(['own', 'none', 'pending_outbound', 'pending_inbound', 'accepted', 'declined', 'revoked']), requestId: Id.nullable(), version: z.number().int().nonnegative() })
export const AgentRuntimeMetadata=z.strictObject({kind:z.literal('external'),protocol:z.literal('chat_completions'),serviceOrigin:z.url().refine(value=>{try{const u=new URL(value);return u.protocol==='https:'&&u.origin===value}catch{return false}}),scope:z.literal('current_message'),credentialPayer:z.literal('agent_owner'),allowAcceptedContacts:z.boolean(),callerAllowed:z.boolean(),requiresConsent:z.literal(true),verification:z.enum(['unverified','passed','failed'])})
export const Contact = z.strictObject({ id: Id, labId: Id, displayName: Title, username:z.string().nullable().default(null), identity: z.discriminatedUnion('kind', [
  z.strictObject({ kind: z.literal('human'), memberId: Id }),
  z.strictObject({ kind: z.literal('personal_agent'), ownerMemberId: Id }),
  z.strictObject({ kind: z.literal('public_agent'), ownerMemberId: Id, capability: PublicCapabilityRef }),
]), agentRuntime:AgentRuntimeMetadata.optional(),availability: ChatAvailability, version: Version, profile: ContactProfile.default({ role: 'human', introduction: '', capabilityDescription: '', personality: '', version: 1 }), relationship: ContactRelationship.default({ status: 'none', requestId: null, version: 0 }), allowedActions: z.array(z.enum(['chat', 'request', 'remove', 'edit_profile', 'manage_private_memory'])).max(5).default([]) })
export const ContactRequest = z.strictObject({ id: Id, requesterMemberId: Id, requesterContactId: Id, targetContactId: Id, deciderMemberId: Id, status: z.enum(['pending', 'accepted', 'declined', 'revoked']), version: Version, createdAt: Instant, updatedAt: Instant, allowedDecisions: z.array(z.enum(['accept', 'decline'])).max(2) })
export const ChatMemoryInput = z.strictObject({ scope: z.enum(['private_agent', 'conversation']), scopeId: Id, content: z.string().trim().min(1).max(2000), source: z.string().max(1000).nullable() })
export const ChatMemory = z.strictObject({ id: Id, scope: z.enum(['private_agent', 'conversation']), scopeId: Id, content: z.string().min(1).max(2000), source: z.string().max(1000).nullable(), status: z.enum(['active', 'revoked']), version: Version, createdByMemberId: Id, createdAt: Instant, updatedAt: Instant, allowedActions: z.array(z.enum(['edit', 'revoke'])).max(2) })
export const ConversationMember = z.strictObject({ contactId: Id, role: z.enum(['owner', 'member']), status: z.enum(['invited', 'joined', 'declined', 'revoked']), version: Version })
export const ConversationViewerState = z.strictObject({ readSequence: z.number().int().nonnegative(), unreadCount: z.number().int().nonnegative(), pinned: z.boolean(), version: Version })
export const Conversation = z.strictObject({ id: Id, labId: Id, kind: z.enum(['personal', 'direct', 'group']), title: Title, ownerMemberId: Id, version: Version, members: z.array(ConversationMember).max(100), taskIds: z.array(Id).max(100), lastSequence: z.number().int().nonnegative(), createdAt: Instant, updatedAt: Instant, allowedActions: z.array(z.enum(['send', 'invite', 'manage', 'manage_memory'])).max(4), viewerState: ConversationViewerState.default({ readSequence: 0, unreadCount: 0, pinned: false, version: 1 }) })
export const Mention = z.strictObject({ contactId: Id, start: z.number().int().nonnegative(), end: z.number().int().positive() })
export const ChatResource = z.strictObject({ kind: z.enum(['plan', 'task', 'assignment', 'run', 'deliverable', 'artifact']), ref: ObjectRef })
export const SharedContext = z.strictObject({ selectedText: Text.nullable(), artifactRefs: z.array(ObjectRef).max(10) })
// These are typed proposals, never executable model tool calls or arbitrary URLs.
export const ChatActionPayload = z.discriminatedUnion('kind', [
  z.strictObject({ kind: z.literal('create_group'), title: Title, plan: ObjectRef, contactIds: z.array(Id).min(1).max(99), sharedContext: SharedContext }),
  z.strictObject({ kind: z.literal('invite_contact'), contactId: Id }),
  z.strictObject({ kind: z.literal('invite_task'), contactId: Id, task: ObjectRef, scope: Text, schedule: Schedule }),
  z.strictObject({ kind: z.literal('run_task'), contactId: Id, task: ObjectRef, capability: PublicCapabilityRef, budget: Budget, inputArtifactRefs: z.array(ObjectRef).max(10) }),
])
export const ChatAction = z.strictObject({ id: Id, conversationId: Id, sourceMessageId: Id, payload: ChatActionPayload, status: z.enum(['proposed', 'applied', 'dismissed', 'stale']), version: Version, createdAt: Instant, expiresAt: Instant, allowedDecisions: z.array(z.enum(['confirm', 'dismiss'])).max(2) })
export const AgentFileMediaType = z.enum(['application/pdf','text/plain','text/markdown','text/csv'])
export const AgentFileMetadata = z.strictObject({messageId:Id,filename:z.string().min(1).max(200),mediaType:AgentFileMediaType,byteLength:z.number().int().min(1).max(10485760),sha256:z.string().regex(/^[a-f0-9]{64}$/),pageCount:z.number().int().min(1).max(200),characterCount:z.number().int().min(1).max(200000)})
export const AgentFileRead = AgentFileMetadata.pick({messageId:true,filename:true,pageCount:true,characterCount:true}).extend({ranges:z.array(z.strictObject({pageNumber:z.number().int().min(1).max(200),start:z.number().int().nonnegative(),end:z.number().int().positive()})).max(20),partial:z.boolean()})
export const AgentFileSelection = z.strictObject({messageId:Id,pageNumbers:z.array(z.number().int().min(1).max(200)).min(1).max(10).optional(),query:z.string().trim().min(1).max(200).optional()})
export const AgentFileMessage = z.strictObject({filename:z.string().min(1).max(200).regex(/^[^\\/\x00-\x1f]+$/),mediaType:AgentFileMediaType,contentBase64:z.string().min(4).max(13981016).regex(/^[A-Za-z0-9+/]*={0,2}$/).refine(value=>value.length%4===0,'Base64 length must be divisible by four'),text:Text.optional()})
export type AgentFileMetadata = z.infer<typeof AgentFileMetadata>
export type AgentFileRead = z.infer<typeof AgentFileRead>
export type AgentFileSelection = z.infer<typeof AgentFileSelection>
export const CreatedAgentReceipt = z.strictObject({ contactId: Id, conversationId: Id, displayName: Title, reused: z.boolean() })
// Absent fields mean reply/null. Do not inject defaults into ordinary API replies:
// already-open 0.14 clients parse those responses using a strict legacy schema.
export const AgentTurn = z.strictObject({ id: Id, conversationId: Id, inputMessageId: Id, agentContactId: Id, purpose: z.enum(['reply','create_agent']).optional(), createdAgent: CreatedAgentReceipt.nullable().optional(), fileRead:AgentFileRead.optional(), status: z.enum(['queued', 'running', 'waiting_input', 'succeeded', 'unavailable', 'failed', 'interrupted', 'cancelled']), failure: z.enum(['MODEL_UNAVAILABLE', 'INVALID_MODEL_OUTPUT', 'MODEL_FAILED', 'LEASE_EXPIRED_USAGE_UNCERTAIN', 'AUTHORITY_CHANGED', 'INPUT_CHANGED', 'BUDGET_EXCEEDED', 'AGENT_LIMIT_REACHED']).nullable(), availability: ChatAvailability, outputMessageId: Id.nullable(), usage: ModelUsage.nullable(), budget: Budget, remainingBudget: Budget.nullable(), allowedActions: z.array(z.enum(['cancel','retry'])).max(2), version: Version, createdAt: Instant, updatedAt: Instant })
export const ChatMessage = z.strictObject({ id: Id, conversationId: Id, sequence: z.number().int().positive(), senderContactId: Id.nullable(), origin: z.enum(['human', 'model', 'service']), files:z.array(AgentFileMetadata).max(1).optional(), text: Text.nullable(), mentions: z.array(Mention).max(20), resources: z.array(ChatResource).max(20), actionIds: z.array(Id).max(10), turnId: Id.nullable(), createdAt: Instant })
export const SendChatMessage = z.strictObject({ text: Text, mentions: z.array(Mention).max(20).default([]), intent: z.enum(['chat', 'ask_agent']).default('chat'), agentContactId: Id.nullable().default(null), budget: Budget.nullable().default(null), context: z.array(ChatResource).max(20).default([]) }).superRefine((v, c) => {
  if (v.intent === 'ask_agent' && (!v.agentContactId || !v.budget)) c.addIssue({ code: 'custom', message: 'Explicit agent and bounded budget required' })
  if (v.intent === 'chat' && (v.agentContactId || v.budget)) c.addIssue({ code: 'custom', message: 'Ordinary chat cannot dispatch an agent' })
  const seen = new Set<string>(); let previousEnd = 0
  for (const mention of v.mentions) {
    if (mention.end <= mention.start || mention.end > v.text.length || mention.start < previousEnd || seen.has(mention.contactId)) c.addIssue({ code: 'custom', message: 'Mentions must be ordered, non-overlapping UTF-16 ranges with unique contacts' })
    previousEnd = mention.end; seen.add(mention.contactId)
  }
})
export type Contact = z.infer<typeof Contact>
export type ContactRequest = z.infer<typeof ContactRequest>
export type ContactProfile = z.infer<typeof ContactProfile>
export type ChatMemory = z.infer<typeof ChatMemory>
export type Conversation = z.infer<typeof Conversation>
export type ConversationViewerState = z.infer<typeof ConversationViewerState>
export type ChatMessage = z.infer<typeof ChatMessage>
export type ChatAction = z.infer<typeof ChatAction>
export type AgentTurn = z.infer<typeof AgentTurn>
export type CreatedAgentReceipt = z.infer<typeof CreatedAgentReceipt>
export type SendChatMessage = z.input<typeof SendChatMessage>

const empty = z.strictObject({})
const id = z.strictObject({ id: Id })
const pagination = z.strictObject({ cursor: z.string().min(1).max(2048).optional(), limit: z.number().int().min(1).max(100).default(30) })
const headers = z.strictObject({ 'Idempotency-Key': z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) })
function route<P extends z.ZodType, Q extends z.ZodType, B extends z.ZodType, R extends z.ZodType>(method: 'GET' | 'POST', path: string, params: P, query: Q, body: B, response: R, status: number, rule: string) {
  return { method, path: `/api/v1${path}`, stage: 'CHAT1' as const, implemented: true, access: 'session', status, rule, idempotent: method !== 'GET', request: z.strictObject({ params, query, body, headers: method === 'GET' ? empty : headers }), response, errors: ErrorResponse, errorStatuses: errorStatus }
}
export const chatRoutes = {
  chatContacts: route('GET', '/chat/contacts', empty, pagination.extend({ search: z.string().max(200).optional(), scope:z.enum(['local','global']).default('local'), view: z.enum(['directory', 'mine']).default('directory') }), z.null(), page(Contact), 200, 'Local directory discovers laboratory identities; mine includes all owned and accepted contacts across spaces. Global scope requires exact username search and returns that human and their personal Agents public profiles only. Relationship, group membership and task authorization are independent. No private memory/history in profiles.'),
  chatContact: route('GET', '/chat/contacts/{id}', id, empty, z.null(), data(Contact), 200, 'Same-lab public profile with actor-specific relationship and allowedActions; stable ID, human/agent kind and immutable role.'),
  updateContactProfile: route('POST', '/chat/contacts/{id}/profile', id, empty, ContactProfileInput.extend({ expectedVersion: Version }), data(Contact), 200, 'Self human or owned agent; public agent requires current lab manager. Version is profile.version. Role/owner/identity cannot be changed. Capability description/personality are user data and do not grant executable capability or override system permissions; edits fence older turns.'),
  createPersonalAgent: route('POST', '/chat/agents', empty, empty, ContactProfileInput, data(Contact), 201, 'Create stable owned personal_agent with specialist role; at most 20 specialist agents per member. Existing unique coordinator remains unchanged. Lab model only; no private tool or capability hosting claim.'),
  requestContact: route('POST', '/chat/contacts/{id}/relationship', id, empty, empty, data(Contact), 200, 'Request human acceptance or private-agent owner approval; published same-lab public agents become accepted directly. Owned agents already own. Exact duplicate cannot create repeated requests. Relationship does not grant private owner memories, group history or task commitment.'),
  contactRequests: route('GET', '/chat/contact-requests', empty, pagination.extend({ direction: z.enum(['all', 'incoming', 'outgoing']).default('all'), status: z.enum(['pending', 'all']).default('pending') }), z.null(), page(ContactRequest), 200, 'Current requester or decider only; pending default, newest request first. Agent-owner decision has no implicit group/history/memory grant.'),
  decideContactRequest: route('POST', '/chat/contact-requests/{id}/decision', id, empty, z.strictObject({ expectedVersion: Version, decision: z.enum(['accept', 'decline']) }), data(ContactRequest), 200, 'Target human or private agent owner only; exact pending version required. Accept establishes contact relationship only. Human relationship is symmetric, agent relationship belongs only to requester.'),
  revokeContact: route('POST', '/chat/contacts/{id}/relationship/revoke', id, empty, z.strictObject({ expectedVersion: Version }), data(Contact), 200, 'Requester or human peer may revoke current relationship with version; owner may revoke private-agent requester relation through contact request decision revoke API. Removes direct chat authority and fences turns, but does not silently withdraw group membership or task commitments.'),
  revokeContactRequest: route('POST', '/chat/contact-requests/{id}/revoke', id, empty, z.strictObject({ expectedVersion: Version }), data(ContactRequest), 200, 'Requester or decider may revoke a pending/accepted relationship, including private-agent owner. Fence direct turns; group membership and task rights stay independently enforced.'),
  chatMemories: route('GET', '/chat/memories', empty, pagination.extend({ scope: z.enum(['private_agent', 'conversation']), scopeId: Id }), z.null(), page(ChatMemory), 200, 'Private-agent memories owner only; conversation memories joined humans only, edit/revoke only current conversation owner. Returns active entries with live ACL and versions; max 10 active entries per scope.'),
  createChatMemory: route('POST', '/chat/memories', empty, empty, ChatMemoryInput, data(ChatMemory), 201, 'Explicit human save only, max 10 active entries per scope. Private-agent owner or joined conversation owner; immutable revision retained. No automatic learning. Scope/owner cannot be supplied differently from the authorized resource.'),
  reviseChatMemory: route('POST', '/chat/memories/{id}/revisions', id, empty, ChatMemoryInput.pick({ content: true, source: true }).extend({ expectedVersion: Version }), data(ChatMemory), 200, 'Current authorized memory manager; exact version and active status. Append revision, fence older model context; scope immutable.'),
  revokeChatMemory: route('POST', '/chat/memories/{id}/revoke', id, empty, z.strictObject({ expectedVersion: Version }), data(ChatMemory), 200, 'Current authorized memory manager; exact version. Soft revoke retains audit revisions but removes content from future model contexts; late old results are fenced.'),
  chatMemoryHistory: route('GET', '/chat/memories/{id}/history', id, empty, z.null(), data(z.strictObject({ memory: ChatMemory, revisions: z.array(ChatMemory).max(100) })), 200, 'Same live scope authority as memories, including after revoke; never lets other users inspect private-agent history. At most 100 revisions per entry.'),
  personalConversation: route('POST', '/chat/personal-conversation', empty, empty, empty, data(z.strictObject({ conversation: Conversation, agent: Contact })), 200, 'Ensure unique personal agent and conversation for current member; never exposes another owner history.'),
  chatConversations: route('GET', '/chat/conversations', empty, pagination, z.null(), page(Conversation), 200, 'Joined human only; own personal assistant first, then viewer-pinned conversations, then updatedAt/id descending. Includes server-persisted actor viewerState; direct title is the opposite human display name. Agent owner authorization alone does not grant browser history.'),
  chatConversation: route('GET', '/chat/conversations/{id}', id, empty, z.null(), data(Conversation), 200, 'Joined human only; invitation or owned joined agent is not browser group history authority. Viewer state and direct title are current actor projections, never shared authority records.'),
  markChatRead: route('POST', '/chat/conversations/{id}/read', id, empty, z.strictObject({ throughSequence: z.number().int().nonnegative() }), data(ConversationViewerState), 200, 'Joined human only; monotonic server-persisted cursor, bounded by current lastSequence. Mark only through messages actually displayed. Exact idempotent replay returns current state and cannot rewind a newer browser cursor. Read progress does not increase preference version; unread counts visible incoming human/model/service messages, excluding own human messages.'),
  updateChatPreferences: route('POST', '/chat/conversations/{id}/preferences', id, empty, z.strictObject({ expectedVersion: Version, pinned: z.boolean() }), data(ConversationViewerState), 200, 'Joined human only; actor-scoped persisted pin preference with optimistic version. Personal assistant is always pinned and cannot be unpinned. Exact replay returns current authorized state; changing pin changes only viewerState.version, never Conversation.version or message ordering.'),
  createDirectConversation: route('POST', '/chat/direct-conversations', empty, empty, z.strictObject({ contactId: Id }), data(Conversation), 200, 'Human pair requires accepted relationship, migration-013-existing pairs backfilled accepted. Own coordinator resolves personal conversation; owned specialists or accepted private/public agent create unique requester-agent direct. Other owners never join requester-agent direct and private owner memory is not shared.'),
  chatMessages: route('GET', '/chat/conversations/{id}/messages', id, pagination.extend({ afterSequence: z.number().int().nonnegative().optional() }), z.null(), page(ChatMessage), 200, 'Authorized immutable messages ordered by sequence; cursor and afterSequence mutually exclusive.'),
  agentChatMessage: route('POST', '/chat/conversations/{id}/agent-messages', id, empty, z.strictObject({text:Text,fileSelection:AgentFileSelection.optional(),externalConsent:z.boolean().optional()}), data(z.strictObject({message:ChatMessage,turn:AgentTurn.nullable()})), 201, 'Natural personal/direct Agent chat, default4000/90. Platform Agent uses sender model and authorized context; only owner coordinator anchored current imperative permits atomic create_agent. External specialist requires externalConsent:true on each message and current owner/accepted-caller policy; sends only this current text to disclosed serviceOrigin, using agent owner credential. No external history/memory/files/tools/tasks or implicit fallback. File selection/attachment and advanced arrangement are not external v1 features. Human SDK messages never invoke this route.'),
  agentFileMessage: route('POST','/chat/conversations/{id}/agent-files',id,empty,AgentFileMessage,data(z.strictObject({message:ChatMessage,turn:AgentTurn.nullable()})),201,'Explicit local file bytes to a personal/direct joined Agent only. Up to10MiB PDF or UTF8 txt/md/csv; isolated bounded text extraction, no URL/OCR. Persist bounded page text privately in turn metadata; API returns metadata only. Default4000/90 budget selects labeled page/UTF16 ranges and partial status. File instructions never authorize tools/contact creation/tasks. Exact replay reauthorizes without parsing or dispatching again. Followup agentChatMessage optionally selects source message/pages/query within the same authorized conversation.'),
  sendChatMessage: route('POST', '/chat/conversations/{id}/messages', id, empty, SendChatMessage, data(z.strictObject({ message: ChatMessage, turn: AgentTurn.nullable() })), 201, 'Persist human message first; explicit ask_agent queues durable turn or returns persisted unavailable turn; ordinary mentions never execute tasks.'),
  chatTurn: route('GET', '/chat/turns/{id}', id, empty, z.null(), data(AgentTurn), 200, 'Conversation ACL and original turn owner only; poll actual model state.'),
  cancelChatTurn: route('POST', '/chat/turns/{id}/cancel', id, empty, z.strictObject({ expectedVersion: Version }), data(AgentTurn), 200, 'Original turn owner; queued/running/waiting_input only; fence late output.'),
  retryChatTurn: route('POST', '/chat/turns/{id}/retry', id, empty, z.strictObject({ expectedVersion: Version, budget: Budget }), data(AgentTurn), 202, 'Explicit owner retry creates new turn against persisted input and reauthorized current context; never automatically retries uncertain usage.'),
  chatActions: route('GET', '/chat/conversations/{id}/actions', id, pagination, z.null(), page(ChatAction), 200, 'Visible proposal and receipt history; allowedDecisions from current business authority, never model assertions.'),
  decideChatAction: route('POST', '/chat/actions/{id}/decision', id, empty, z.strictObject({ expectedVersion: Version, expectedConversationVersion: Version, decision: z.enum(['confirm', 'dismiss']) }), data(z.strictObject({ action: ChatAction, conversationId: Id, resources: z.array(ChatResource).max(100) })), 200, 'Confirm exact immutable proposal only; transaction rechecks ACL/versions and invokes canonical task commands; receipt links authority objects.'),
  chatInvitations: route('GET', '/chat/invitations', empty, pagination, z.null(), page(z.strictObject({ id: Id, conversationId: Id, title: Title, invitedContactId: Id, invitedByMemberId: Id, status: z.enum(['pending', 'accepted', 'declined', 'revoked']), version: Version })), 200, 'Current invitee or invited agent owner; summary only before acceptance.'),
  decideChatInvitation: route('POST', '/chat/invitations/{id}/decision', id, empty, z.strictObject({ expectedVersion: Version, decision: z.enum(['accept', 'decline']) }), data(ConversationMember), 200, 'Human invitee or personal agent owner only; accepting an agent invitation authorizes only that agent in this group. The owner browser requires a separate joined human membership to read history. Neither acceptance shares owner private history or accepts task commitment.'),
  revokeChatMember: route('POST', '/chat/conversations/{id}/members/{contactId}/revoke', z.strictObject({ id: Id, contactId: Id }), empty, z.strictObject({ expectedVersion: Version, expectedConversationVersion: Version, reason: Text }), data(ConversationMember), 200, 'Group owner; revoke membership, fence turns, invalidate group projections. Canonical task permissions remain independently enforced; no silent withdrawal of accepted commitments.'),
} as const
