import { z } from 'zod'
import { Id, Title, Version, Instant, ErrorResponse, errorStatus, data } from './models.js'

export const ModelProvider=z.enum(['deepseek','qwen','doubao'])
export const ProviderModel=z.string().regex(/^[A-Za-z0-9][A-Za-z0-9_.:-]{0,127}$/)
export const PersonalModelInput = z.strictObject({ name:Title, provider:ModelProvider, model:ProviderModel, enabled:z.boolean(), apiKey:z.string().min(8).max(512).optional(), removeApiKey:z.boolean().optional() }).refine(v=>v.provider!=='deepseek'||['deepseek-flash','deepseek-v4-pro'].includes(v.model), 'Unsupported DeepSeek model')
export const PersonalModelConfiguration = z.strictObject({ id:Id, name:Title, provider:ModelProvider, model:ProviderModel, baseUrl:z.enum(['https://api.deepseek.com/anthropic','https://dashscope.aliyuncs.com/compatible-mode/v1','https://ark.cn-beijing.volces.com/api/v3']), enabled:z.boolean(), hasApiKey:z.boolean(), isDefault:z.boolean(), version:Version, createdAt:Instant, updatedAt:Instant })
export const PersonalModelSettings = z.strictObject({ configurations:z.array(PersonalModelConfiguration).max(20), version:z.number().int().nonnegative(), platformEnabled:z.boolean(), defaultConfigurationId:Id.nullable(), source:z.enum(['personal','legacy_lab','unconfigured']), legacyLabAvailable:z.boolean() })
const empty=z.strictObject({}), id=z.strictObject({id:Id}), headers=z.strictObject({'Idempotency-Key':z.string().regex(/^[A-Za-z0-9_-]{16,128}$/)})
function route<P extends z.ZodType,B extends z.ZodType,R extends z.ZodType>(method:'GET'|'POST'|'PATCH',path:string,params:P,body:B,response:R,status:number,rule:string){return {method,path:`/api/v1${path}`,stage:'B5b' as const,implemented:true,access:'session',status,rule,idempotent:method!=='GET',request:z.strictObject({params,query:empty,headers:method==='GET'?empty:headers,body}),response,errors:ErrorResponse,errorStatuses:errorStatus}}
export const personalModelRoutes={
 personalModels:route('GET','/me/model-configurations',empty,z.null(),data(PersonalModelSettings),200,'Self-only metadata; never returns secret or ciphertext. Personal configurations take precedence over legacy laboratory configuration; isolated public accounts cannot use laboratory credentials.'),
 createPersonalModel:route('POST','/me/model-configurations',empty,PersonalModelInput,data(PersonalModelConfiguration),201,'Self only, max20. First active configuration becomes the default. Encrypted key bound to member and configuration identity; provider/model must be implemented. Key omitted means unset; no secret in receipt.'),
 updatePersonalModel:route('PATCH','/me/model-configurations/{id}',id,PersonalModelInput.safeExtend({expectedVersion:Version}),data(PersonalModelConfiguration),200,'Self only and exact configuration version. Omitted apiKey preserves secret; removeApiKey explicitly revokes while disabled. All changes fence prior model turns; response only hasApiKey.'),
 deletePersonalModel:route('POST','/me/model-configurations/{id}/delete',id,z.strictObject({expectedVersion:Version}),data(PersonalModelSettings),200,'Self only and exact version; delete encrypted key and configuration. Default deletion leaves no selected configuration; no automatic fallback to another user or laboratory credential while personal records remain.'),
 defaultPersonalModel:route('POST','/me/model-configurations/default',empty,z.strictObject({expectedVersion:z.number().int().nonnegative(),configurationId:Id.nullable()}),data(PersonalModelSettings),200,'Self only; expectedVersion is PersonalModelSettings.version. Select an existing enabled configuration with a usable key, or null to clear. Changes fence queued/running older selection, retaining actual usage; explicit personal selection never falls back to a laboratory secret.'),
} as const
