import {z} from 'zod'
import {Id,Title,Text,Version,Instant,ErrorResponse,errorStatus,data,page} from './models.js'
import {Contact,Conversation} from './chat.js'

export const WorkspacePerson=z.strictObject({contactId:Id,displayName:Title,kind:z.enum(['human','agent']),status:z.enum(['invited','accepted','declined','revoked'])})
export const WorkResult=z.strictObject({messageId:Id.nullable(),deliverableId:Id.nullable(),summary:Text,accepted:z.boolean()})
export const PersonalWorkTask=z.strictObject({id:Id,title:Title,goal:Text.nullable(),owner:WorkspacePerson,participants:z.array(WorkspacePerson).max(100),status:z.enum(['proposed','ready','running','blocked','awaiting_review','completed','cancelled']),summaryOnly:z.boolean(),conversationId:Id.nullable(),sourceConversationId:Id.nullable(),sourceMessageId:Id.nullable(),agentContactId:Id.nullable(),turnId:Id.nullable(),result:WorkResult.nullable(),version:Version,createdAt:Instant,updatedAt:Instant,allowedActions:z.array(z.enum(['activate','accept','decline','run','submit','review','cancel','invite'])).max(8)})
export const WorkbenchCard=z.strictObject({id:Id,source:z.enum(['research_task','personal_task','followup']),taskId:Id.nullable(),title:Title,goal:Text.nullable(),category:z.enum(['ongoing','awaiting_me','completed','scheduled']),status:z.string().max(80),owner:WorkspacePerson,participants:z.array(WorkspacePerson).max(100),summaryOnly:z.boolean(),progress:z.strictObject({completed:z.number().int().nonnegative(),total:z.number().int().nonnegative(),label:z.string().max(200)}),result:WorkResult.nullable(),conversationId:Id.nullable(),version:Version,updatedAt:Instant,allowedActions:z.array(z.string().max(80)).max(20)})
export const CapabilityPublication=z.strictObject({id:Id,contactId:Id,status:z.enum(['published','withdrawn']),contact:Contact,tags:z.array(z.string().trim().min(1).max(40)).max(8),version:Version,createdAt:Instant,updatedAt:Instant,allowedActions:z.array(z.enum(['publish','withdraw'])).max(2)})
export type PersonalWorkTask=z.infer<typeof PersonalWorkTask>
export type WorkbenchCard=z.infer<typeof WorkbenchCard>
export type CapabilityPublication=z.infer<typeof CapabilityPublication>
const empty=z.strictObject({}),id=z.strictObject({id:Id}),headers=z.strictObject({'Idempotency-Key':z.string().regex(/^[A-Za-z0-9_-]{16,128}$/)}),pagination=z.strictObject({cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(100).default(30)})
function route<P extends z.ZodType,Q extends z.ZodType,B extends z.ZodType,R extends z.ZodType>(method:'GET'|'POST',path:string,params:P,query:Q,body:B,response:R,status:number,rule:string){return {method,path:'/api/v1'+path,stage:'CHAT1' as const,implemented:true,access:'session',status,rule,idempotent:method!=='GET',request:z.strictObject({params,query,headers:method==='GET'?empty:headers,body}),response,errors:ErrorResponse,errorStatuses:errorStatus}}
export const workspaceRoutes={
 workbench:route('GET','/me/workbench',empty,pagination.extend({category:z.enum(['all','ongoing','awaiting_me','completed','scheduled']).default('all')}),z.null(),page(WorkbenchCard),200,'Aggregate current authorized research tasks, durable personal work and actual schedules; successful execution requires explicit result acceptance before completed.'),
 personalWorkTask:route('GET','/work/tasks/{id}',id,empty,z.null(),data(PersonalWorkTask),200,'Owner or invited participant only; invitation exposes title and participation summary, not goal/results until accepted.'),
 createPersonalWorkTask:route('POST','/work/tasks',empty,empty,z.strictObject({title:Title,goal:Text,contactIds:z.array(Id).max(99),agentContactId:Id.nullable().default(null)}),data(PersonalWorkTask),201,'Create an owned durable proposal, no model call or automatic membership. Only own contacts or accepted human/Agent contacts; no research-material grant.'),
 activatePersonalWorkTask:route('POST','/work/tasks/{id}/activate',id,empty,z.strictObject({expectedVersion:Version}),data(PersonalWorkTask),200,'Owner confirms task and creates canonical social group with independent membership invitations. Accepted contacts only; no automatic acceptance on behalf of another human/Agent owner.'),
 decidePersonalWorkTask:route('POST','/work/tasks/{id}/participation',id,empty,z.strictObject({expectedVersion:Version,decision:z.enum(['accept','decline'])}),data(PersonalWorkTask),200,'Current human accepts only own task participation; group membership is a separate invitation and grants no research task/material access.'),
 invitePersonalWorkContact:route('POST','/work/tasks/{id}/invite',id,empty,z.strictObject({expectedVersion:Version,contactId:Id}),data(PersonalWorkTask),200,'Owner invites an accepted contact; Agent participation remains subject to its owner accepting the canonical group invitation.'),
 runPersonalWorkTask:route('POST','/work/tasks/{id}/run',id,empty,z.strictObject({expectedVersion:Version,agentContactId:Id}),data(PersonalWorkTask),200,'Owner/accepted human explicitly submits the full task goal to a joined local Agent using the sender model and bounded4000/90 budget; no external implicit forwarding or tool execution.'),
 submitPersonalWorkResult:route('POST','/work/tasks/{id}/result',id,empty,z.strictObject({expectedVersion:Version,text:Text}),data(PersonalWorkTask),200,'Owner/accepted human posts actual result to the canonical conversation; does not mark accepted/completed.'),
 reviewPersonalWorkResult:route('POST','/work/tasks/{id}/review',id,empty,z.strictObject({expectedVersion:Version,messageId:Id,decision:z.enum(['accept','request_changes'])}),data(PersonalWorkTask),200,'Owner reviews the current exact authorized canonical result. Only acceptance marks completed.'),
 cancelPersonalWorkTask:route('POST','/work/tasks/{id}/cancel',id,empty,z.strictObject({expectedVersion:Version}),data(PersonalWorkTask),200,'Owner cancellation fences active associated turns and preserves messages, usage and results.'),
 capabilityPublications:route('GET','/capability-square',empty,pagination.extend({view:z.enum(['public','mine']).default('public'),kind:z.enum(['all','human','agent']).default('all'),search:z.string().max(100).default('')}),z.null(),page(CapabilityPublication),200,'Only explicitly published, currently active owner capability profiles across spaces. No private memories, conversations or connection credentials. Current relationship actions are reprojected.'),
 capabilityPublication:route('GET','/capability-square/{id}',id,empty,z.null(),data(CapabilityPublication),200,'Published public profile; withdrawn is owner-only. Adding and chatting reuse actual contact request/accept/direct routes.'),
 publishCapability:route('POST','/capability-square',empty,empty,z.strictObject({contactId:Id,expectedVersion:z.number().int().nonnegative(),tags:z.array(z.string().trim().min(1).max(40)).max(8)}),data(CapabilityPublication),200,'Owner explicitly publishes current own human or personal Agent profile; expectedVersion0 creates, otherwise updates/re-publishes. No implicit publication on registration/import.'),
 withdrawCapability:route('POST','/capability-square/{id}/withdraw',id,empty,z.strictObject({expectedVersion:Version}),data(CapabilityPublication),200,'Owner withdraws discovery immediately including old cursors; existing accepted relationships remain independently managed.'),
 socialConversation:route('GET','/work/tasks/{id}/conversation',id,empty,z.null(),data(Conversation),200,'Current joined human only; pending task/group invitation cannot read history. Social membership does not expand research task or material ACL.'),
} as const
